### ISSUE TITLE
EMT on linux

### ISSUE THREAD

**Issue by gbetrie** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#104]
Hello,

I'm using Matlab R2014a on linux to run EMT v2.1.6. EMT crushes when it tries to load input file for testing (d=epanet('Net1.inp'). This happen at line 480 of epanet.m. Could you please help?

Thanks,
Get

**Comment by Mariosmsk** [comment]
Hi @gbetrie, 

I have tested with `MATLAB-R2014b` on `glnxa64` and it works (EMT2.1.6). Maybe you need to follow notes for the folder `glnx`:
- unzip libepanet
- run terminal
- sudo cp libepanet.so /lib64/libepanet.so
- sudo rm libepanet.so
