### ISSUE TITLE
How can i find the flowpath?

### ISSUE THREAD

**Issue by Alexandroz** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#11]

**Comment by Alexandroz** [comment]
Is there any way that i can find to which nodes the flow is goes in the network?

**Comment by eldemet** [comment]
Hm, I suppose the easiest way is to simulate a non-reacting species, to create a map of where the flow is going and with what percentage. Is that what you asked?

**Comment by Alexandroz** [comment]
I suppose this would help, but is there another way to find the sequence of the nodes that are receiving water. I am using a single period analysis . Is this possible to do , a water quality analysis in single period?
