### ISSUE TITLE
setNodeDemandPatternIndex of individual patterns in the same node?

### ISSUE THREAD

**Issue by jonas1790** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#15]
Hi,

assuming a node has two demand categories assigned (including different base demands A and B and time patterns Aa and Bb). In such a case it is possible to retrieve the number of demand categories (2) inside the node and get the individual demands A and B. It is also possible to change the individual demands A and B.

However, is it also possible to change the individual time patterns Aa and Bb (by not modifying the .inp file)? I can only see to change one of them, e.g. by using setNodeDemandPatternIndex.

Thanks in advance,

Jonas

**Comment by Mariosmsk** [comment]
Hi Jonas, 

I have updated the function setNodeDemandPatternIndex (dev-2.1b), so you can edit the demand patern index for a junction that already has categories.

**Comment by jonas1790** [comment]
Hi Marios,

perfect - _ENsetdemandpattern_ was exactly the function that I missed :) 
Thanks a lot!
