### ISSUE TITLE
a confict between addNodeJunction and  closeNetwork.

### ISSUE THREAD

**Issue by lookforhan** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#151]
**Describe the bug**

The matlab will crash when the addNodeJunction and closeNetwork run in sequence,

**To Reproduce**

you can reproduce the crash as follows:
`
d = epanet('Net1.inp');

d.addNodeJunction('j1');

d.closeNetwork;
`
**Screenshots**

**Desktop (please complete the following information):**

MATLAB 版本: 9.6.0.1174912 (R2019a) Update 5
MATLAB 许可证编号: 40759243
操作系统: Microsoft Windows 10 家庭版 Version 10.0 (Build 18362)
Java 版本: Java 1.8.0_181-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
epanet version  is 2.1.8
**Additional context**

I have contact with Matlab Technical Support Team, And here is the reply:
"It appears the crash is related to the third party toolkit, OpenWaterAnalytics/​EPANET-Matlab-Toolkit. Therefore, to resolve this issue, contact the 3rd party who creates this toolkit. "

**Comment by Mariosmsk** [comment]
We will check this bug! Thanks!

**Comment by Mariosmsk** [comment]
I have tested with Matlab 32bit it works fine.  But with Matlab 64bit crashed.

**Comment by Mariosmsk** [comment]
After tests again works ok. You can use `d.unload` instead `d.closeNetwork` for now.

**Comment by lookforhan** [comment]
Hi @Mariosmsk ，
Thanks for reply.
It works fine when I use d.unload.
But here is the problem "the report file is needed  which is generated with the d.closeNetwork."

**Comment by Mariosmsk** [comment]
To generate a report file you can check the function `d.writeReport`:
```
            % Example:
            d = epanet('Net1.inp');
            d.solveCompleteHydraulics;
            d.solveCompleteQuality;
            d.setReportFormatReset
            d.setReport('FILE TestReport3.txt'); 
            d.setReport('NODES ALL')
            d.setReport('LINKS ALL')
            d.writeReport	           
            open('TestReport3.txt')
```
or you can use the function:

`d.runsCompleteSimulation('results');` % using a name of report and binary files  `results.txt`,  `results.bin` 

`d.runsCompleteSimulation;` % you can check the default report & binary files `network_temp.txt`, `network_temp.bin`

**Comment by lookforhan** [comment]
OK，@Mariosmsk 
thanks for the reply.
I would try it,
