### ISSUE TITLE
change pipe (LinkNodesIndex,NodesConnectingLinksID,NodesConnectingLinksIndex)

### ISSUE THREAD

**Issue by mohammedpopo** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#159]
if I have four node
Pipe 1 from Node 1 to Node 2
Pipe 2 from Node 2 to Node 3
Pipe 3 from Node 3 to Node 4
Pipe 4 from Node 4 to Node 1
if
i Would like to connect Pipe 2 from Node 1 to Node 3
How Could I Do that 
i Tried to Change NodesConnectingLinksID (Done)
I Tried to Change LinkNodesIndex (NOT)
i Tried to Change NodesConnectingLinksIndex (Not)

Finally, I Found the Problem 
('Assignment not supported because the result of method 'getLinkNodesIndex' is a temporary value.')

**Comment by Mariosmsk** [comment]
Hi @mohammedpopo, 

You can check the example 23 here: 
https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/blob/dev-2.2-edit/examples/EX23_Change_connection_links.m

Using the functions 
`d.getLinkNodesIndex`
`d.setLinkNodesIndex`

Please download the dev branch to test this example: 
https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/tree/dev-2.2-edit

**Comment by mohammedpopo** [comment]
I tried this example as it is 
it shows me 
"Error using epanet/getLinkNodesIndex
Too many input arguments.
Error in EX8_tanks_to_reservoirs (line 145)
linkNodes = d.getLinkNodesIndex(linkIndex);"

**Comment by Mariosmsk** [comment]
Please make sure to download the dev branch. Because I have made some updates.
https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/tree/dev-2.2-edit
