### ISSUE TITLE
setDemandModel function

### ISSUE THREAD

**Issue by mohammedpopo** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#160]
In setDemandModel function 
There are two pressure required to proceeds with the function
                  pmin - Pressure below which there is no demand
                  preq - Pressure required to deliver full demand
My Question Which NHFR that it use to simulate the network??

NHFR's are (Bhave, Germanopoulos, Salgado-Castro, Wagner, Fujiwara, and Li, Tanyimboh &   Templeman) Which one the code use?

Thanks in advance,

**Comment by Mariosmsk** [comment]
More info for the `demand model` you can find here: https://github.com/OpenWaterAnalytics/EPANET/blob/dev/ReleaseNotes2_2.md#pressure-dependent-demands
