### ISSUE TITLE
look

### ISSUE THREAD

**Issue by lookforhan** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#161]
I am prepared to write an article by using the EPANET-Matlab-Toolkit, while some problems emerged. The problems are described as followed:
1. One of the benchmarks, which is named "ZJ.inp", is used for testing, While I did not find the reference information about it. It is in "EPANET-Matlab-Toolkit/networks/asce-tf-wdst/ZJ/" . I hope that you may provide some information about ZI.inp.
2. I hope to cite your work, while I can not find the paper  "EPANET-MATLAB Toolkit: An Open-Source Software for Interfacing EPANET with MATLAB" through the internet. And I did not find it through the doi. Please send me a copy of the paper if possible. You can send the copy to my email, which is 767122454@qq.com.
look forward to your reply.
best wishes to you.

**Comment by Mariosmsk** [comment]
Hi @lookforhan, 

1. I have added a file named `Sources.md` which references the source or contributor of each network. https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/blob/dev-2.2-edit/networks/asce-tf-wdst/Sources.md

2. You can find the paper here: [EPANET-Matlab-Toolkit-paper](https://zenodo.org/record/831493)

Regards,
Marios

**Comment by lookforhan** [comment]
HI @Mariosmsk ,
Thank you very much, it's really helpful!!
