### ISSUE TITLE
Setting flow units changes the initial status of links

### ISSUE THREAD

**Issue by stephen-young** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#166]
**The bug**
I am using the EMT to execute a hydraulic analysis of a network under several scenarios. For the purposes of the analysis, I need the flow units to cubic metres per hour (CMH). In order to guarantee the correct flow units returned from `getComputedHydraulicTimeSeries`, I use the `setBinFlowUnitsCMH` method of the `epanet` class. The bug I have noticed is that every link that has an initial status of 'CLOSED' changes to 'OPEN' after calling `setBinFlowUnitsCMH`. 

**To Reproduce**
```MATLAB
hydro_net = epanet('Net1.inp')
initLinkStatus = hydro_net.getLinkInitialStatus() % initLinkStatus should be all ones
hydro_net.setLinkInitialStatus(zeros(1,hydro_net.LinkCount)) % Close all the links in the network
initLinkStatus = hydro_net.getLinkInitialStatus() % initLinkStatus should now be all zeros
hydro_net.setBinFlowUnitsCMH()
initLinkStatus = hydro_net.getLinkInitialStatus() % initLinkStatus returns as all ones
```

**Desktop**
- OS: Windows 10 Version 1909 (OS Build 18363.592)
- MATLAB version: 9.6.0.1114505 (R2019a) Update 2
- epanet version: 2.1.8.1

**Additional context**
A workaround I'm currently using is to collect the initial status of every non-CV link in the network with `getLinkInitialStatus` before calling `setBinFlowUnitsCMH` and then re-applying the initial status with `setLinkInitialStatus`.

Am I missing something?

**Comment by Mariosmsk** [comment]
Hi @stephen-young,

If you use the `bin` with `normal` functions you need to call the function `saveInputFile`.

You can use here the updated version with v2.2 dlls of the EPANET libraries.
https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/tree/dev-2.2-edit

**With v2.2 you can use the Example 2 with only normal EPANET functions. I suggest it.** 
Also for hydraulic analysis, you can check all functions for compute time series with tic/toc to select the better for you `d.getComputedTime` (tab)

Example 1:
```
hydro_net = epanet('Net1.inp');
initLinkStatus1 = hydro_net.getLinkInitialStatus() % initLinkStatus should be all ones
hydro_net.setLinkInitialStatus(zeros(1,hydro_net.LinkCount)); % Close all the links in the network
initLinkStatus2 = hydro_net.getLinkInitialStatus() % initLinkStatus should now be all zeros
hydro_net.saveInputFile(hydro_net.TempInpFile);
hydro_net.setBinFlowUnitsCMH();
initLinkStatus3 = hydro_net.getLinkInitialStatus() % initLinkStatus returns as all ones
```

Example 2:
```
hydro_net = epanet('Net1.inp');
initLinkStatus1 = hydro_net.getLinkInitialStatus() % initLinkStatus should be all ones
hydro_net.setLinkInitialStatus(zeros(1,hydro_net.LinkCount)); % Close all the links in the network
initLinkStatus2 = hydro_net.getLinkInitialStatus() % initLinkStatus should now be all zeros
hydro_net.setFlowUnitsCMH();
initLinkStatus3 = hydro_net.getLinkInitialStatus() % initLinkStatus returns as all ones
```
