### ISSUE TITLE
Add getPumpSwitches

### ISSUE THREAD

**Issue by Mohammed-Abdallah** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#17]
Hello

Thanks for this great project. Please can you add function which calculate the number of pump switches (pump status change from off to on) ? I think it is very useful specially for people who are looking to optimize pump switches.

Thanks

**Comment by Mariosmsk** [comment]
Hi, 

The function getLinkPumpSwitches has now been added to the [EMT dev-2.1b](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/tree/dev-2.1b).

Best regards,
Marios
