### ISSUE TITLE
Prototype file is missing for running deployed

### ISSUE THREAD

**Issue by stephen-young** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#172]
Loading the epanet C library in the `epanet` class is done differently when the library is deployed in a compiled application or library from the MATLAB compiler ([see line 13710 of `epanet.m`](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/blob/7f77945351f2382315a9aec88dea9becd2e0e79d/epanet_matlab_toolkit/epanet.m#L13710)) than when in a MATLAB session. 

The signature of the `loadlibrary` function being used if the library is deployed appears to be on that requires a ["prototype file"](https://www.mathworks.com/help/matlab/ref/loadlibrary.html#btgwx_a-1) called `mxepanet` but the file cannot be found and does not appear to be in the repository.

If this file is meant to be generated by the user before compilation, can you please advise how to make this file?

**Comment by stephen-young** [comment]
I did some more reading in MATLAB's documenation and  the prototype file can be [generated with the `loadlibrary` function](https://www.mathworks.com/help/matlab/matlab_external/prototype-files.html#btjpwwf).

**Comment by Mariosmsk** [comment]
https://www.youtube.com/watch?v=Qf8_hgYxGyM
