### ISSUE TITLE
I found a bug in controls EMT-2.1.8

### ISSUE THREAD

**Issue by peiman94** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#174]
If our network has controls for the pumps, when we delete a number of mains pipes and add some valves to them, the controls change and the controls are applied to the valves instead of the pump.
My guess is that this happens by changing the pump index.
I hope I have achieved my goal.

**Default network controls:**
'LINK PMP-1 OPEN IF NODE T-1 BELOW 28.8696'
'LINK PMP-1 CLOSED IF NODE T-1 ABOVE 31.308'
'LINK PMP-2 OPEN IF NODE T-1 BELOW 27.3456'
'LINK PMP-2 CLOSED IF NODE T-1 ABOVE 31.0032'
**Controls after removing a number of pipes and adding valves:**
'LINK PRV-9   IF NODE T-1 BELOW 28.8696'
'LINK PRV-9 CLOSED IF NODE T-1 ABOVE 31.308'
'LINK PRV-10   IF NODE T-1 BELOW 27.3456'
'LINK PRV-10 CLOSED IF NODE T-1 ABOVE 31.0032'

**Comment by Mariosmsk** [comment]
Please check the newest version of EMT  https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/tree/dev-2.2-edit
