### ISSUE TITLE
Problem or bug in the pump with variable speed v2.2

### ISSUE THREAD

**Issue by peiman94** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#175]
In a network with 2 pumps, I have defined a pattern for changing the speed of the pumps; When I define the control for opening or closing the pumps, In some time steps the pump speed is considered to be the default value of 1 or even 0, while the value of 0 or 1 is not present in the pattern given to the pump. What is the cause of this? Is it a bug?

The speed of the pump obtained at the end(d.getLinkSettings):
![1](https://user-images.githubusercontent.com/75311695/101243167-8d550e00-3713-11eb-91e8-8cfa7753f614.jpg)
Defined pattern for pumps:
![2](https://user-images.githubusercontent.com/75311695/101243172-9645df80-3713-11eb-8f94-4fae4a858fd3.jpg)
**As you can see, in some time steps, instead of the values given to the pump (Figure 2), the speed values of the pumps are considered 0 or 1.**

**Comment by Mariosmsk** [comment]
Hi @peiman94, I have tested with Net1 (1 pump), and looks ok! You can try the below example

```
d = epanet('Net1.inp');
pt =[0.3342, 0.9184, 1.0119, 1.6807, 0.8807, 1.2345, 2.3191, 1.4168];
% add new pattern
d.addPattern('patPump', pt);
pumpIndex = d.getLinkPumpIndex;

% set pattern at pump
d.setLinkPumpPatternIndex(pumpIndex(1), 2)
% compute time series
res = d.getComputedTimeSeries;

% get settings
plot(res.Setting(:, d.getLinkPumpIndex))
res.Setting(:, d.getLinkPumpIndex)

d.unload;

```
```
ans =

    0.3342
    0.3342
    0.9184
    0.9184
    1.0119
    1.0119
    1.6807
    1.6807
    0.8807
    0.8807
    1.2345
    1.2345
    2.3191
    2.3191
    1.4168
    1.4168
    0.3342
    0.3342
    0.9184
    0.9184
    1.0119
    1.0119
    1.6807
    1.6807
    0.8807

```
![image](https://user-images.githubusercontent.com/2945956/101291235-f28e2980-380f-11eb-8977-f8ef3c4c10ab.png)

**Comment by peiman94** [comment]
Hi @Mariosmsk . I wrote the exact same code, but I see the values 0, 1 in the results. If possible, I will send the network to you to take a look. Thanks a lot.
Code I wrote:
```
X3= [2.1014    1.1003    1.9161    0.7100    1.4782    0.3342    0.9184    1.0119    1.6807    0.8807    1.2345    2.3191    1.4168    0.4505    1.3531 1.5811    2.5284    1.1198    2.5188    1.8273    0.4468    1.0020    1.8906    1.5953    0.8364    0.9453    2.4065    1.9667 0.6891    2.2336 1.3841    1.5484    2.2097    1.3833    0.3388    0.5015    1.8959    1.5042    2.8019    0.5562    1.3136    1.7742    0.6015    2.7421    2.0098 2.7446    2.0025    0.3384    1.1545    0.6021];
PI=d.getLinkPumpIndex;
d.addPattern('Pump1Pattern',X3(1:25));
d.addPattern('Pump2Pattern',X3(26:50));
d.setLinkPumpPatternIndex(PI,[12,13]);
%%%Network Analysis
d.openHydraulicAnalysis;
d.initializeHydraulicAnalysis;
tstep=1;P=[];LinkSettings=[];
while (tstep>0)
    t=d.runHydraulicAnalysis;
    P=[P; d.getNodePressure];
    LinkSettings=[LinkSettings; d.getLinkSettings];
    tstep=d.nextHydraulicAnalysisStep;
end
d.closeHydraulicAnalysis;
```

[Ex4-1PA.zip](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/files/5652315/Ex4-1PA.zip)

**Comment by Mariosmsk** [comment]
@peiman94 , I think this depends on the controls of your pumps, tank level, etc. If you remove controls of your input file it's ok.
You can add the following line in your code:
`d.deleteControls()`

**Comment by peiman94** [comment]
@Mariosmsk ,So the values it shows are correct? Does that mean there is no bug? I can not delete the network controls for some reason because I need them. There are two ways that this is a bug in the toolkit and needs to be fixed or that the results I got are correct. Which one? Regards.

**Comment by allenmlowe** [comment]
This issue is related to []((https://github.com/OpenWaterAnalytics/EPANET/issues/558))

**Comment by allenmlowe** [comment]
This issue is related to [(https://github.com/OpenWaterAnalytics/EPANET/issues/558)](url)
