### ISSUE TITLE
bug in calculate pressure

### ISSUE THREAD

**Issue by hossain93** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#176]
I analyse a network in epanet and then analys this network in matlab but dosn't exist right answer because when I compare pressures in both they are not same. I analys network Net1.inp in path EPANET-Matlab-Toolkit-dev-2.2-edit\networks\epanet-desktop\Net1

this is my code
`clc;

clear all;

d = epanet('Net1.inp');

d.solveCompleteHydraulics;

ID=d.getNodeJunctionNameID;

[rID,cID]=size(ID);

P=d.getNodePressure;

[rP,cP]=size(P);

 P(:,[cID+1,cP])=[ ];% delet tank and reservoir pressure's

 ID=str2double(ID);% 

for i=1:cID

   pressure(i,2)=P(1,i);

   pressure(i,1)=ID(1,i);

end`

and in this table I compare pressure
![image](https://user-images.githubusercontent.com/77359545/104428849-335d2900-559a-11eb-868d-02fd233f10d6.png)

**Comment by Mariosmsk** [comment]
Hi @hossain93 , 

With EPANET 2.2 

 EPANET Example Network 1
Network Table - Nodes at 24:00 Hrs
                        	Pressure        
 Node ID                	psi             
Junc 10                 	125.9684        
Junc 11                 	117.4695        
Junc 12                 	115.0309        
Junc 13                 	116.6872        
Junc 21                 	115.7436        
Junc 22                 	116.7866        
Junc 23                 	118.7622        
Junc 31                 	113.9308        
Junc 32                 	108.8426        

Is the same. 

I think you compare the wrong times. The time is 24hrs based n your matlab code.
