### ISSUE TITLE
Is there a specific setting to run a quality analysis?

### ISSUE THREAD

**Issue by jorgeps86** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#177]
Hi community,
I was trying example 14 to run a hydraulic and quality analysis with the toolkit (v2.2). However, after implementing the code, I get zeros for the d.getNodeActualQuality variable. Is there an initial setting I'm missing? or do I need to export the original inp file with the quality field different than None?

Any assistance is highly appreciated.
Jorge Pesantez

**Comment by Mariosmsk** [comment]
Hi @jorgeps86, must be call the function `d.setQualityType`. If the quality options parameter is None not working for quality.
Also, you can check the example https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/blob/dev-2.2-edit/examples/EX16_create_multiple_scenarios.m

![image](https://user-images.githubusercontent.com/2945956/105612943-08f44280-5dc8-11eb-9076-c795613ff5c3.png)

```
d.setQualityType('Chlorine', 'mg/L');
initialQuality = 0.6;
nodeIndex = d.getNodeReservoirIndex;
nodeIndex = [nodeIndex d.getNodeTankIndex];
d.setNodeInitialQuality(nodeIndex, initialQuality * ones(length(nodeIndex),1))
```

Regards,
Marios
