### ISSUE TITLE
Converting an existing node to either a tank or reservoir

### ISSUE THREAD

**Issue by maserukabendicto** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#178]
Hello @eldemet and @Mariosmsk ,

Is it possible to add functions that convert;
- existing nodes to either tanks or reservoir
- existing nodes to either reservoir
- existing reservoirs and tanks to nodes

These could be similar to setLinkTypePipe, setLinkTypePump, setLinkTypeValveTCV, setLinkTypeValvePRV.

regards,
Ben

**Comment by Mariosmsk** [comment]
Hi @maserukabendicto, 
https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/blob/dev/ReleaseNotes2_2_1.md
