### ISSUE TITLE
No appropriate method, property, or field 'getLinkLenght' for class 'epanet'

### ISSUE THREAD

**Issue by esilvapino** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#181]
Hello, I need use d.getLinLength en my code. Resulting this error.

No appropriate method, property, or field
'getLinkLenght' for class 'epanet'.

Error in AlgGen (line 48)
L=d.getLinkLenght(1:nLineas);

But in the Command windows, no give error.

![image](https://user-images.githubusercontent.com/28302510/123143401-8d56fa00-d428-11eb-9701-bc1987ef9119.png)

How could i solve it?.

Thanks.

**Comment by Mariosmsk** [comment]
The function method is `L=d.getLinkLength`
