### ISSUE TITLE
How can we use multi-threaded version of EPANET in Matlab?

### ISSUE THREAD

**Issue by sdlj2008** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#182]
In EPANET 2.2 multiple projects can be analyzed in parallel in a thread-safe manner. Is EMT applied  to multi-threaded version of EPANET? If yes, how to achieve this？If not, how can we implement parallel in Matlab?

**Comment by Mariosmsk** [comment]
[EX24_using_parfor](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/blob/master/examples/EX24_using_parfor.m)
