### ISSUE TITLE
Connectivity Matrix and number of pipes

### ISSUE THREAD

**Issue by eldemet** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#193]
I think there is a bug in the connectivty matrix

g = epanet('ky2.inp')
A = g.getConnectivityMatrix
G = graph(A)

ans = 
  graph with properties:
    Edges: [1116×2 table]
    Nodes: [815×2 table]

however
>> g.getLinkPipeCount
ans =
        1124
>> g.getNodeCount
ans =
   815

**Comment by eldemet** [comment]
Probably this happens when there are nodes with 2 pipes in parallel

**Comment by Mariosmsk** [comment]
fixed by increasing the weight of the edge line
![image](https://user-images.githubusercontent.com/2945956/151714756-4bcc37a3-2e36-4ac6-82bc-8533bea60fba.png)

**Comment by Mariosmsk** [comment]
```
d = epanet('ky2.inp');
A = d.getConnectivityMatrix;
G = graph(A);

l = d.getLinkCount;
n = d.getNodeCount;

hh = find(G.Edges.Weight>1);
hh = G.Edges(hh,:).EndNodes;
hh1 = hh(:, 1);
hh2 = hh(:, 2);
h = plot(G, 'EdgeLabel', G.Edges.Weight)
highlight(h, hh1, hh2, 'EdgeColor', 'red')

```
