### ISSUE TITLE
error with kernel32.lib

### ISSUE THREAD

**Issue by alireza2032** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#22]
Hi, 
Recetly when I run my codes get the below error. I updated the epanet.m and epanet.dll files from lastest version on your website. (Github link) but it didn't solve.
Regards, 
Alireza
 

Error using loadlibrary (line 422)
Building epanet2_thunk_pcwin64 failed.  Compiler output is:
cl -I"C:\Program Files\MATLAB\R2014a\extern\inc lude"  /W3  /nologo  /D_CRT_SECURE_NO_DEPRECATE
/D_SCL_SECURE_NO_DEPRECATE /D_SECURE_SCL=0   -I"C:\Program Files\MATLAB\R2014a\extern\include" -I"C:\Program
Files\MATLAB\R2014a\simulink\i nclude" -I"F:\alireza\EPANET-Matlab-Toolkit-master\EPANET-Matlab-Toolkit-master"
-I"F:\alireza\EPANET-Matlab-Toolkit-master\EPANET-Matlab-Toolkit-master\64bit" "epanet2_thunk_pcwin64.c" -LD
-Fe"epanet2_thunk_pcwin64.dll"
epanet2_thunk_pcwin64.c
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'

Error in epanet>ENLoadLibrary (line 6917)
            loadlibrary([LibEPANETpath,Lib EPANET],[LibEPANETpath,LibEPAN ET,'.h']);

Error in epanet (line 463)
            ENLoadLibrary(obj.LibEPANETpat h,obj.LibEPANET);

Error in testBinFunctions (line 14)
tic;d=epanet(inpname);toc

**Comment by eldemet** [comment]
Hi, it could be an issue with your compiler.

Could you please tell us what you get when running this command: 

mex -setup

**Comment by alireza2032** [comment]
When I running mex -setup I get this messages: 

![1](https://user-images.githubusercontent.com/23118656/33364934-c66aa254-d4fb-11e7-809f-33725bb577e3.JPG)

Thanks,

**Comment by Mariosmsk** [comment]
Hi @alireza2032, 

Select Microsoft Windows SDK 7.1
This is my result:
![image](https://user-images.githubusercontent.com/2945956/33425937-e9578b1a-d5c8-11e7-939c-5370652e81b4.png)

Or you need to reinstall sdk.. 
http://www.microsoft.com/en-us/download/details.aspx?id=8279
(If you prefer you can also download the ISO file, and use WinCDEmu to mount it.)
http://download.microsoft.com/download/F/1/0/F10113F5-B750-4969-A255-274341AC6BCE/GRMSDKX_EN_DVD.iso
WARNING: if you experience problems in installing the SDK, perhaps you are using a newer version of the “Microsoft Visual C++ 2010 Redistributable” compiler than the SDK is using. Just uninstal the previous x86 and x64 version and re-install.

**Comment by Mariosmsk** [comment]
Also, other compiler. 
[Mingw-w64-c-c-compiler](https://www.mathworks.com/matlabcentral/fileexchange/52848-matlab-support-for-mingw-w64-c-c-compiler)
[https://www.youtube.com/watch?v=iUO_a41b3j8](https://www.youtube.com/watch?v=iUO_a41b3j8)
