### ISSUE TITLE
Speeding Up EPANET-MATLAB 

### ISSUE THREAD

**Issue by agill3399** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#227]
I may be missing some functionality that has already been created but I am trying to write some code that will quickly and efficiently process user inputs from a matlab app dashboard, and passing them into a function that calls the EPANET-MATLAB Toolkit. Right now my extended period analysis runs around 37 seconds, and my steady state analysis runs around 10-11 seconds (these both include file loading times and toolkit path generation). 

EPANET by itself runs very quickly (2 seconds tops) for a 72 hour simulation for example. I am not sure about the nuts and bolts of how matlab is processing the .inp file so that is why I am posting. Any ideas? Maybe some of the EN_ functions may help but I am also having trouble getting those functions to work. 

Thanks for your help!

**Comment by Mariosmsk** [comment]
Hi @agill3399, please, can you send me an example/sample of your code? I will try to help you. mariosmsk@gmail.com

Regards, 
Marios

**Comment by Mariosmsk** [comment]
This is solved, so we close!
