### ISSUE TITLE
don't work function 'getComputedHydraulicTimeSeries' 

### ISSUE THREAD

**Issue by soheil687681** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#229]
**Describe the bug**i change pattern vector by function 'setPattern(patternIndex,patternVector)' but the function of 'getComputedHydraulicTimeSeries'  return  value of  constant pressure in output.
please help me to solve it

**To Reproduce**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by alireza2032** [comment]
Hi @soheil687681 

I checked your problem. The setPattern function work correctly. 
Maybe you need to download the last update of epanet.m.
