### ISSUE TITLE
Issues with addBinTank

### ISSUE THREAD

**Issue by kafakiran** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#23]
Hello,

With the below code 1, I try to place some number of tanks (numtank) with random places and random H, D values. All tanks are successfully placed however the first one's coordinates are not entered to the inp file so I have to make a correction using the second code below. 

Is this a bug or am I doing something wrong?

Another thing, is it possible to place multiple tanks with a single addBinTank command or do I have to make a for loop? addBinTank gets really slow when the network gets bigger (~1 second for 10-20 nodes while ~45 seconds for ~500 nodes).

I am running Matlab R2017a by the way.

Thanks in advance for the answers.

%% CODE 1 %%

nj=epa.getNodeJunctionCount;
nr=epa.getNodeReservoirCount;
    numtank=randi([1 nj],1);
    odn=1:1:nj;
    odnara=odn(randperm(length(odn)));
    odnson=odnara(1:numtank);
    Tsel=randi([1 80],1,numtank);
    Hsel=typtank(Tsel,1);
    Dsel=typtank(Tsel,2);

for k=1:numtank
    
    epa.addBinTank(strcat('T',num2str(odnson(k))),epa.getNodeCoordinates{1}(odnson(k))+10,epa.getNodeCoordinates{2}(odnson(k))+10,...
    Hsel(k),Dsel(k),1,epa.getNodeElevations(odnson(1,k)),0,0,0,strcat('DB',num2str(odnson(1,k))),cell2mat(epa.getNodeNameID(odnson(1,k))),1,1000,130,'PIPE');

end

%% CODE 1 %%

%% CODE 2 %%

nt=epa.getNodeTankCount;
    epa.setNodeCoordinates((nj+nr+nt),[epa.getNodeCoordinates{1}(odnson(1))+10,epa.getNodeCoordinates{2}(odnson(1))+10]);

%% CODE 2 %%

**Comment by Mariosmsk** [comment]
Hello @kafakiran, 

Replace your loop with code below:

> for k=1:numtank
> 
>     tankId = ['T',num2str(odnson(k))];
>     nTankIndex = epa.addNodeTank(tankId);
>     epa.setNodeCoordinates(nTankIndex,[epa.getNodeCoordinates{1}(odnson(k))+10,epa.getNodeCoordinates{2}(odnson(k))+10]);
>     epa.setNodeTankMaximumWaterLevel(nTankIndex, Hsel(k))
>     epa.setNodeTankDiameter(nTankIndex, Dsel(k))
>     epa.setNodeTankInitialLevel(nTankIndex, 0)
>     epa.setNodeElevations(nTankIndex, epa.getNodeElevations(odnson(1,k)))
>     epa.setNodeInitialQuality(nTankIndex, 0)
>     epa.setNodeTankMinimumWaterLevel(nTankIndex, 0)
>     epa.setNodeTankMinimumWaterVolume(nTankIndex, 0)
>     
>     nPipeIndex=epa.addLinkPipe(strcat('DB',num2str(odnson(1,k))),tankId,cell2mat(epa.getNodeNameID(odnson(1,k))));
>     epa.setLinkLength(nPipeIndex, 1)
>     epa.setLinkDiameter(nPipeIndex, 1000)
>     epa.setLinkRoughnessCoeff(nPipeIndex, 130)
> end

**Comment by kafakiran** [comment]
the above provided code works much faster now however the performance changes when the network gets bigger. 

For example it takes around 0.05 seconds to place one tank to a network with 100 nodes, while it takes around 1 second to place a tank to a network with 1800 nodes.

Is there any more ways to make speed improvements?

Thanks.

**Comment by kafakiran** [comment]
Branch EMT 2.1.6 works much faster than the original code, so I close this issue for now.

Thanks.
