### ISSUE TITLE
Input Error 251: function call contains invalid parameter code.

### ISSUE THREAD

**Issue by kafakiran** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#24]
Is there any detailed explanation about the error "Input Error 251: function call contains invalid parameter code."?

I am getting it as a warning during long iterations, and I don't know if it affects any of my calculations as my code keeps on running.

Also I am getting it during the long iterations as an error when executing "setNodeTankMaximumWaterLevel" command. However it appears sometimes not always.

If I can get more information about the error code maybe I can figure out my mistake(s).

Thanks in advance.

**Comment by Mariosmsk** [comment]
Maximum Water level > Minimum Water level and Initial Water Level
