### ISSUE TITLE
setControls function

### ISSUE THREAD

**Issue by eldemet** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#25]
@Mariosmsk, it would be great if we had a more user-friendly setControls function, which takes as argument a structure which desribes the controls (or even more complex rules).

**Comment by Mariosmsk** [comment]
@eldemet,  example with new function setControls:

> d.setControls(1, 'LINK 9 CLOSED IF NODE 2 ABOVE 180')
> %or
> %set many controls
> controls = d.getControls;
> d.setControls(controls)

> d.getControls(1)
> 
> ans = 
> 
>        Type: 'HIGHLEVEL'
>      LinkID: '9'
>     Setting: 'CLOSED'
>      NodeID: '2'
>       Value: 180
>     Control: 'LINK 9 CLOSED IF NODE 2 ABOVE 180'

What do you think now?
[EMT2.1.6](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit)

**Comment by eldemet** [comment]
Hm, it looks good. Does it work with all types of control?

**Comment by Mariosmsk** [comment]
Yes, also you can do:

> c = d.getControls;
> d.setControls({c.Control}) 
> d.setControls({'LINK 9 OPEN IF NODE 2 BELOW 110', 'LINK 9 CLOSED IF NODE 2 ABOVE 200', 'LINK 12 CLOSED AT CLOCKTIME 10'})

**Comment by Mariosmsk** [comment]
Note: update d.getControls https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/commit/6741e786df91ed112623c4cf3b2b97fcd9135e97
