### ISSUE TITLE
Loading the network inside a for loop

### ISSUE THREAD

**Issue by kafakiran** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#27]
I try to run a for loop which needs to start with a predefined initial "network0.inp", makes some random changes and computations on this network and moves to the next one. 

Instead of opening the netwotk inside the for loop with `epa=epanet('network0.inp')`, I define a variable epa0 at the beginning which opens the network, and inside the for loop I call this initial network with `epa=epa0`.

However this epa variable gets stuck to the previous network parameters unless I run an additional code like `epa.setBinFlowUnitsLPS` after `epa=epa0`. Is this some kind of a bug or am I doing something wrong?

Also is there any alternative way to call the initial network parameters within a for loop?

Thanks.

**Comment by kafakiran** [comment]
Let me simplify my question. 

Is it possible to load two different inp files at the same time and use them interchangeably?

**Comment by Mariosmsk** [comment]
Hi @kafakiran, 
Try to use this example. Is not possible but with this "hack" its ok.
[example](https://htmlpreview.github.io/?https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/blob/EMT-2.1.6/examples/html/load2diffINP.html)

**Comment by kafakiran** [comment]
The solution by @Mariosmsk works fine as explained however it still did not solve my real problem.

Nevertheless, I replaced epa.setBinFlowUnitsLPS with epa.setBinTimeReportingStep(3600) which worked well with a considerable increase in the speed.

I don't know the reason why it works but it works for now.
Thanks anyway:)
