### ISSUE TITLE
Help troubleshooting recent MATLAB crash

### ISSUE THREAD

**Issue by Abdul-2018** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#29]
Hi,
I have this recurrent problem when I am using the EPANET-Matlab-Toolkit, I already contacted MathWorks Technical Support team and their response was:

We understand that you are facing an issue using the ‘EPANET-Matlab-Toolkit’ found in the MATLAB File Exchange. We have been able to reproduce the crash that you are facing and identified that the crash occurs in the ‘runHydraulicAnalysis’ command in the ‘EPANET-Matlab-Toolkit’. We believe that the authors of the toolkit would be better equipped to provide a solution in this case, and therefore recommend contacting the authors to further pursue this issue. We have also captured the information from your use case and will forward it to the developers.

I attached some of the crush report samples:
[mathworks_Zeinab.log](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/files/2255430/mathworks_Zeinab.log)

[matlab crash.txt](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/files/2255448/matlab.crash.txt)

Thanks in advance!

**Comment by Mariosmsk** [comment]
Hi @Abdul-2018, 

You can tell us more information about this. What do you run first? How did you use the function runHydraulicAnalysis? Anyway, I close this issue. If the problem still exists then you can reopen or create a new issue.  

Thanks, 
Marios
