### ISSUE TITLE
 contaminant propagation time

### ISSUE THREAD

**Issue by sm2017** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#30]
I have a network ,
How can I calculate contaminant propagation time in each pipe  ? By epanet 
only or by epanet-matlab toolkit.

More explain:

I want to have contaminant propagation time in each pipe , assuming that contaminant transportation takes place with a velocity equal to the flow velocity of water.there can be multiple patches within different propagation time from a node to corresponding downstream nodes. The path which takes minimum time for propagation of contaminant is chosen and corresponding time is noted.

**Comment by Mariosmsk** [comment]
Hi @sm2017, 

example: 

> start_toolkit;
> d = epanet('Net1.inp');
> d.setQualityType('chem','mg/L');
> initqual_values = d.getNodeInitialQuality * 0;
> 
> node_res_index = d.getNodeReservoirIndex;
> node_res_index = node_res_index(1); % first reservoir
> d.setNodeSourceType(node_res_index,'SETPOINT');
> 
> % Add contaminant in reservoir
> contaminant_value = 1; %mg/l
> initqual_values(node_res_index)=contaminant_value;
> d.setNodeInitialQuality(initqual_values);
> d.setNodeSourceQuality(initqual_values);
> % d.getNodeSourceQuality
> 
> res = d.getComputedTimeSeries; % using ENepanet binary file
> nodeQuality = res.NodeQuality;
> 
> checkContaminantTimeInput = nodeQuality>0;
> detectTimes = NaN(1, d.NodeCount);
> 
> fprintf('Contaminant propagation:');
> for i=1:d.NodeCount
>     contpropagation = find(checkContaminantTimeInput(:,i), 1);
>     if ~isempty(contpropagation)
>         detectTimes(i) = res.Time(contpropagation);
>         fprintf(['\n\tFrom Node ', char(d.NodeNameID(i)),...
>         ' at time ', num2str(detectTimes(i)), ' (seconds).']);
>     end
> end
> fprintf('\n');
> 
> d.unload;

Also, [EPANET-MATLAB Toolkit: An Open-Source Software for
Interfacing EPANET with MATLAB](https://github.com/KIOS-Research/CCWI2016/blob/master/CCWI2016/Paper/Eliades2016.pdf)
I hope this help.

Thanks, 
Marios

**Comment by sm2017** [comment]
Hi @Mariosmsk  , thanks alot.

**Comment by sm2017** [comment]
Is there alternative simpler solution?

**Comment by sm2017** [comment]
Is there alternative simpler solution?
