### ISSUE TITLE
getLinkVelocity command

### ISSUE THREAD

**Issue by kenwaka** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#31]
Hi everyone
I want to have the speed of the water in each tube, I wrote these commands

d=epanet('3_BWSN_Network_2.inp');
[v=d.getLinkVelocity;

But everything is zero!! What should I do to get the right answer?
my network is  
in file Sensor Placement (BWSN)  :  [BWSN2](https://emps.exeter.ac.uk/engineering/research/cws/downloads/benchmarks/)

thanks alot

**Comment by Mariosmsk** [comment]
Hi @kenwaka,

> % d = epanet('3_BWSN_Network_2.inp');
> % or  load network without calculate properties, only load
> d = epanet('3_BWSN_Network_2.inp', 'loadfile');
> 
> 
> %example 1
> res = d.getComputedTimeSeries; %ignore events
> 
> Velocity1 = res.Velocity;
> 
> 
> %example 2
> %For step by step Hydraulic Analysis
> d.openHydraulicAnalysis;
> d.initializeHydraulicAnalysis;
> tstep=1;V=[];T_H=[];
> while (tstep>0)
>     t=d.runHydraulicAnalysis;
>     V=[V; d.getLinkVelocity];
>     T_H=[T_H; t];
>     tstep=d.nextHydraulicAnalysisStep;
> end
> d.closeHydraulicAnalysis
> 
> Velocity2 = V;

(Flows, velocity, headloss, status, setting, energy, quality for links are computed values.
Demand, head, pressure, quality, quality, source mass for nodes are computed values.)

**Comment by kenwaka** [comment]
Hi & Good  Mariosmsk  :-)
Thank you very very much for your answer , it's helpful.
