### ISSUE TITLE
EPANET MSX error 

### ISSUE THREAD

**Issue by fbrin** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#34]
Hello everyone,

I was hoping someone could help me out. I am running the code test on matlab but when it is time to test multispecies extension, i get the following errors:

Error 501 - insufficient memory available.
Error 502 - no EPANET data file supplied.
Error 503 - could not open MSX input file.
Error 504 - could not open hydraulic results file.
Error 505 - could not read hydraulic results file.
Error 506 - could not read MSX input file.
Error 507 - too few pipe reaction expressions.
Error 508 - too few tank reaction expressions.
Error 509 - could not open differential equation solver.
Error 510 - could not open algebraic equation solver.
Error 511 - could not open binary results file.
Error 512 - read/write error on binary results file.
Error 513 - could not integrate reaction rate expressions.
Error 514 - could not solve reaction equilibrium expressions.
Error 515 - reference made to an unknown type of object.
Error 516 - reference made to an illegal object index.
Error 517 - reference made to an undefined object ID.
Error 518 - invalid property values were specified.
Error 519 - an MSX project was not opened.
Error 520 - an MSX project is already opened.
Error 521 - could not open MSX report file.
Error 522 - could not compile chemistry functions.
Error 523 - could not load functions from compiled chemistry file.
Error 524 - illegal math operation.

Then I hit enter again to continue and get the next ones pops up:

Error using open (line 86)
File 'reportmsx.txt' not found.

Error in testMSXFunctions (line 168)
open(rptmsx);

Error in RunTests (line 9)
testMSXFunctions

Any ideas? Any help is very appreciated. Thanks evryone

**Comment by fbrin** [comment]
Thank you. I was able to run it on my other computer running on Linux and got the EPANET part to work. EPANET MSX does not. Apparently test.m script is looking for the .so files but the files are there. I extracted the libepanet.so files and placed it into the 64bits folder but still not working. These is the error now:

Error using loadlibrary
There was an error loading the library "/home/fbrinn/Documents/EPANET-Matlab-Toolkit-2.1.1/glnx/epanetmsx.so"
libepanet.so: cannot open shared object file: No such file or directory

Error in epanet>MSXMatlabSetup (line 7265)
    loadlibrary([obj.MSXLibEPANETPath,obj.MSXLibEPANET],[obj.MSXLibEPANETPath,[obj.MSXLibEPANET,'.h']]);

Error in epanet/loadMSXFile (line 2670)
                MSXMatlabSetup(obj,msxname);

Error in testMSXFunctions (line 21)
d.loadMSXFile(msxname);

Error in RunTests (line 9)
testMSXFunctions

Caused by:
    Error using loaddefinedlibrary
    libepanet.so: cannot open shared object file: No such file or directory

**Comment by Mariosmsk** [comment]
I have confused. Are you use the EMT on Windows or Linux? For Linux maybe need to follow this for the error (first issue)

> Error using open (line 86)
> File 'reportmsx.txt' not found.
> 
> Error in testMSXFunctions (line 168)
> open(rptmsx);

right click on the file epanetmsx > properties > tab permissions > select allow executing file as program.  

for issue 2:
Delete the file libepanet.so from folder glnx.
