### ISSUE TITLE
Is it possible to open .NET file in EPANET-MATLAB toolkit ?

### ISSUE THREAD

**Issue by linkhochon** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#39]
Hi everyone, 

I have a water distribution network of .NET type.

in the 'How to use the Toolkit' ,There is an example 
Example:

d=epanet('Net1.inp')

d.getNodeCount

d.getNodeElevations

Does this toolkit  only run .inp files?
i want to use some function of this toolkit, and I don't want to convert my .net file too.
Is there a way to use these functions without changing the file type? 

Thanks

**Comment by Mariosmsk** [comment]
No, is not possible. Why you don' t convert .net? It's easy using EPANET GUI
![screenshot_2](https://user-images.githubusercontent.com/2945956/44993503-7eff7100-afa3-11e8-97cb-270c683ad187.png)

**Comment by linkhochon** [comment]
Hi @Mariosmsk  , thanks. Have a nice time.
