### ISSUE TITLE
Reseting the input file using EPANET-Matlab-Toolkit

### ISSUE THREAD

**Issue by Abdul-2018** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#40]
Hi @Mariosmsk ,
I am optimizing a network operations and topology, so I am adding, deleting, and changing the settings of the network components. My question is how could I reset the network (input file) to the original setting and topology after the changes happened at each iteration without loading the original input file at each iteration.
I tried to use (d.loadEPANETFile(d.InputFile)) at the beginning and(d.closeNetwork;) at the end of the objective function to reset the network at each iteration but that resulted in Matlab to crash after few seconds and provide me with this message (MATLAB has encountered an internal problem and needs to close) and the crash report stated that there is an (Access violation detected) .
Thanks,
Abdul

**Comment by Mariosmsk** [comment]
Hi @Abdul-2018 , 

I hope you using the version EMT2.1.6 because in the dev2.2 branch we make changes. Try to use `d.loadEPANETFile(d.BinTempfile) ` at the beginning without `d.closeNetwork;` . 

Regards, 
Marios

**Comment by Abdul-2018** [comment]
Thank you, but now I am having anothe issue which is [Failure in user-supplied fitness function evaluation. Cannot continue.] caused by a file error (303) after some generations as shown here from the command window :
_________________________________________________________________________________________________
EPANET loaded sucessfuly.
Input File "anytown.inp" loaded sucessfuly.
Warning: MATLAB has disabled some advanced graphics rendering features by switching to software OpenGL. For more information, click here. 

                              Average            Average
Generation   Func-count    Pareto distance    Pareto spread
    1           101                 1                 1
    2           201                 0                 0
File Error 303: cannot open report file.
Index exceeds array bounds.
...
_______________________________________________________________________________________________

I do not know if it is memory issue or coding issue, any help will be appreciated. Thanks!

**Comment by Mariosmsk** [comment]
@Abdul-2018, Are you using d.addBinJunction or d.addNodeJunction (or remove via bin) ? An example of your code? (send to me if you want mariosmsk@gmail.com)

**Comment by Abdul-2018** [comment]
@Mariosmsk ,I am only using the normal functions like (d.addNodeJunction, and d.deleteLink) and used d.loadEPANETFile(d.BinTempfile) at the beginning.  Should I use (Bin Functions) as I am working on the (d.BinTempfile) file. I have send you an email.Thanks

**Comment by Mariosmsk** [comment]
@Abdul-2018, it's ok using normal functions.

**Comment by Abdul-2018** [comment]
@Mariosmsk , Is there a limit for calling the binary temporary file ( d.BinTempfile) or using (d.loadEPANETFile) function?.
Thanks

**Comment by Abdul-2018** [comment]
@Mariosmsk , Is it a bug in the library or what do you think?

**Comment by Mariosmsk** [comment]
@Abdul-2018 , Maybe by mistakes you deleted all data from the network?
`System Error 102: no network data available.
`
