### ISSUE TITLE
getLinkNodesIndex    with flow direction 

### ISSUE THREAD

**Issue by linkhochon** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#41]
I'm working on this network 
[d-town.zip](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/files/2388220/d-town.zip)

i want to have  start node and final node for all  links. 

my try 
d= epanet('d-town.inp');
I=d.getLinkNodesIndex;

i got  the following result
[result.xlsx](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/files/2388226/result.xlsx

but this result is not true! why?

for example  we have  200 -199 in first row.
but in newtork , junction 200 connected to junction 198 and junction 1154.

i want to have   the indexes of the from/to nodes of all links in directed graph.( after ran the network ).

for example, for this grah ,
![capture](https://user-images.githubusercontent.com/29150324/45620235-732aa900-ba91-11e8-8dcb-6c265eb703a0.PNG)
, I want  a result like the following 
T1-j39
j39-j24
j24-j337
j337-j336
j336-j335
j335-j333
j333-j334
j336-j204
j341-j204

How can I get such results?
After the hydraulic analysis of the network , we have  the flow of water. in fact we have a digraph . 
i want the link indexes  according to its direction.

**Comment by Mariosmsk** [comment]
Your results are the indices of nodes, not the IDs. Check this functions to get IDs d.getNodesConnectingLinksID

**Comment by Mariosmsk** [comment]
This is not according to the direction of flow. Is the start and end of the pipes.

**Comment by Mariosmsk** [comment]
Check this:
```
d = epanet('d-town.inp', 'epanet2');

% hydraulic simulation
res = d.getComputedTimeSeries; % ignore events
%d.getComputedHydraulicTimeSeries with events.

flows = res.Flow;

res_direct = min(flows);

NodesConnectingLinksID = d.getNodesConnectingLinksID;

directionsAfterSimulation = {};
for i = 1:d.getLinkCount
    if res_direct(i) > 0
        directionsAfterSimulation(i, :) = NodesConnectingLinksID(i, :);
    else
        directionsAfterSimulation(i, :) = fliplr(NodesConnectingLinksID(i, :));
    end 
end

directionsAfterSimulation
```

I hope this helps,
Marios

**Comment by linkhochon** [comment]
Hi @Mariosmsk

i have  one error 'Index exceeds array bounds.'  for this network 
[ky8.txt](https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/files/2408513/ky8.txt)

![capture](https://user-images.githubusercontent.com/29150324/45925428-dd27d000-bf21-11e8-8c44-13bce18e6c9e.PNG)

i don't understand why i have this error , what should i do?

thanks & Best

**Comment by linkhochon** [comment]
@Mariosmsk  thanks a lot , I can't thank you enough .
