### ISSUE TITLE
transfer time

### ISSUE THREAD

**Issue by kenwaka** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#42]
Hi,
is there a command which calculate  the water transfer time from node 'i' to node 'j' (transfer time in each pipe)? 
![ex](https://user-images.githubusercontent.com/42710063/46902114-45882280-cecc-11e8-9a16-466069f74df2.PNG)

For example, in the above image, the time for water transfer from node 5 to 17 is one minute, it is 28 minute from node 6 to node 13.
I want to get the transfer time for different networks,
 I searched the internet and saw the software guide, but I did not find anything good.
Is there a command in TM to use it?

**Comment by kenwaka** [comment]
Could anyone recommende a good  source for learning about this toolkit?

**Comment by Mariosmsk** [comment]
this issue moved here: http://community.wateranalytics.org/t/water-transfer-time-in-each-pipe-whats-the-unit-of-velocity-and-length-in-getlinkvelocity-and-getlinklength/726/6
