### ISSUE TITLE
New functions EMT v2.2

### ISSUE THREAD

**Issue by Mariosmsk** [OpenWaterAnalytics/EPANET-Matlab-Toolkit#47]
1. - [x] ENsetflowunits	Sets the project's flow units
2. - [x] ENaddnode	Adds a new node to a project
3. - [x] ENaddlink	Adds a new link to a project
4. - [x] ENaddcontrol	Adds a new simple control to a project
5. - [x] ENaddrule	Adds a new control rule to a project
6. - [x] ENdeletenode	Deletes a node from the project
7. - [x] ENdeletelink	Deletes a link from the project
8. - [x] ENdeletepattern	Deletes a time pattern from the project
9. - [x] ENdeletecurve	Deletes a data curve from the project
10. - [x] ENdeletecontrol	Deletes a simple control from the project
11. - [x] ENdeleterule	Deletes a rule-based control from the project
12. - [x] ENsetnodeid	Changes the ID name for a node
13. - [x] ENsetjuncdata	Sets values for a junction's parameters
14. - [x] ENsettankdata	Sets values for a tank's parameters
15. - [x] ENsetlinkid	Changes the ID name for a link
16. - [x] ENsetlinknodes	Sets a link's start- and end-nodes
17. - [x] ENsetlinktype	Changes the type of a specific link
18. - [x] ENsetpipedata	Sets values for a pipe's parameters
19. - [x] ENgetdemandmodel	Retrieves the type of demand model in use
20. - [x] ENsetdemandmodel	Sets the type of demand model to use
21. - [x] ENadddemand	Adds a new demand category to a node
22. - [x] ENdeletedemand	Deletes a demand category from a node
23. - [x] ENgetdemandindex	Finds a demand category's index given its name
24. - [x] ENgetdemandname	Gets the name of a node's demand category
25. - [x] ENsetdemandname	Sets the name of a node's demand category
26. - [x] ENsetdemandpattern	Assigns a time pattern to a node's demand category
27. - [x] ENsetpatternid	Changes the ID name of a time pattern
28. - [x] ENsetcurveid	Changes the ID name of a data curve
29. - [x] ENgetcurvetype	Gets a curve's type
30. - [x] ENsetheadcurveindex	Sets the index of a head curve used by a pump
31. - [x] ENgetruleinfo	Gets the number of elements in a rule-based control
32. - [x] ENgetruleid	Gets the name assigned to a rule-based control
33. - [x] ENgetpremise	Gets the contents of a premise in a rule-based control
34. - [x] ENsetpremise	Sets the contents of a premise in a rule-based control
35. - [x] ENsetpremiseindex	Sets the index of an object in a premise of a rule-based control
36. - [x] ENsetpremisestatus	Sets the status of an object in a premise of a rule-based control
37. - [x] ENsetpremisevalue	Sets the value of a property in a premise of a rule-based control
38. - [x] ENgetthenaction	Gets the contents of a THEN action in a rule-based control
39. - [x] ENsetthenaction	Sets the contents of a THEN action in a rule-based control
40. - [x] ENgetelseaction	Gets the contents of an ELSE action in a rule-based control
41. - [x] ENsetelseaction	Sets the contents of an ELSE action in a rule-based control
42. - [x] ENsetrulepriority	Sets the priority of a rule-based control
43. - [x] ENgettitle	Gets a project's title
44. - [x] ENsettitle	Sets a project's title
45. - [x] ENgetcomment	Gets the descriptive comment assigned to an object
46. - [x] ENsetcomment	Assigns a descriptive comment to an object
47. - [x] ENcopyreport Copies the contents of a project's report file
48. - [x] EN_clearreport  Clears the contents of a project's report file

**Comment by Mariosmsk** [comment]
https://github.com/OpenWaterAnalytics/EPANET/wiki/New-in-2.2

**Comment by AndreasAshikkis** [comment]
Functions that have been added:

1) ENsetcurveid
2) ENgetdemandindex
3) ENadddemand
4) ENdeletedemand

**Comment by AndreasAshikkis** [comment]
1. ENsettankdata
2. ENsetpatternid

**Comment by AndreasAshikkis** [comment]
1. ENsetlinknodes
2. ENsetpipedata

**Comment by AndreasAshikkis** [comment]
1. ENaddrule
2. ENgetpremise
3. ENgetthenaction
4. ENsetthenaction
5. ENgetelseaction
6. ENsetelseaction
7. ENsetrulepriority

**Comment by AndreasAshikkis** [comment]
1. ENsetpremise
2. ENsetpremiseindex
3. ENsetpremisestatus
4. ENsetpremisevalue

**Comment by AndreasAshikkis** [comment]
1. ENcopyreport
2. EN_clearreport

**Comment by Mariosmsk** [comment]
Done! @AndreasAshikkis
